### ISSUE TITLE
Unable to preregister as attendee

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#27]
```
Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 249, in with_session
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 353, in with_rendering
    return render(_get_template_filename(func), result)
  File "/app/plugins/uber/uber/decorators.py", line 274, in render
    rendered = template.render(data)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/plugins/uber/uber/templates/preregistration/index.html", line 1, in top-level template code
    {% extends "./preregistration/preregbase.html" %}
  File "/app/plugins/uber/uber/templates/preregistration/preregbase.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/app/plugins/uber/uber/templates/base.html", line 229, in top-level template code
    {% block content %}{% endblock %}
  File "/app/plugins/uber/uber/templates/preregistration/index.html", line 62, in block "content"
    {% if charge.total_cost > 0 %}
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/app/sideboard/lib/_utils.py", line 82, in caching
    setattr(self, pname, func(self, *args, **kwargs))
  File "/app/plugins/uber/uber/utils.py", line 324, in total_cost
    return 100 * sum(m.amount_unpaid for m in self.models)
  File "/app/sideboard/lib/_utils.py", line 82, in caching
    setattr(self, pname, func(self, *args, **kwargs))
  File "/app/plugins/uber/uber/utils.py", line 352, in models
    return self.from_sessionized(self._targets)
  File "/app/plugins/uber/uber/utils.py", line 281, in from_sessionized
    return [cls.from_sessionized(t) for t in d]
  File "/app/plugins/uber/uber/utils.py", line 281, in <listcomp>
    return [cls.from_sessionized(t) for t in d]
  File "/app/plugins/uber/uber/utils.py", line 287, in from_sessionized
    return cls.from_sessionized_attendee(d)
  File "/app/plugins/uber/uber/utils.py", line 300, in from_sessionized_attendee
    return sa.Attendee(**d)
  File "<string>", line 4, in __init__
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/app/sideboard/lib/sa/__init__.py", line 215, in __init__
    declarative_base_constructor(self, *args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/ext/declarative/base.py", line 653, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'promo_code' is an invalid keyword argument for Attendee
```

**Comment by jmdawson** [comment]
Fixed by related commit.
