### ISSUE TITLE
Crash when Submitting a new artist of all types 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#272]
on submit of a new artist   via http://rams.test.furfest.org/rams/art_show_applications/

I get this error on 
http://rams.test.furfest.org/rams/art_show_applications/index

*** Error message ***
Please contact us via https://www.furfest.org if you're not sure why you're seeing this page.
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 478, in with_timed
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 504, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 631, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 559, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/art_show/art_show/site_sections/art_show_applications.py", line 30, in index
    attendee, message = session.attendee_from_art_show_app(**params)
TypeError: 'NoneType' object is not iterable
Powered by CherryPy 17.3.0

*** End message ***

**Comment by Hugmonster** [comment]
@kitsuta  Tagging you at Crimson's request

**Comment by kitsuta** [comment]
Should be fixed by the next round of updates.
