### ISSUE TITLE
RAMS Throws exception trace when sending rejection emails

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#51]
Unclear what else this affects, but it throws these in the logs ever 15 minutes or so:

```
web_1    | 2017-11-14T02:37:17.720440846Z error sending 'Your Midwest FurFest Art Show application has been declined' email to gingeegirls@gmail.com
web_1    | 2017-11-14T02:37:17.720465446Z Traceback (most recent call last):
web_1    | 2017-11-14T02:37:17.720469517Z   File "/app/plugins/uber/uber/automated_emails.py", line 156, in really_send
web_1    | 2017-11-14T02:37:17.720472863Z     self.render(model_instance), format,
web_1    | 2017-11-14T02:37:17.720475779Z   File "/app/plugins/uber/uber/automated_emails.py", line 140, in render
web_1    | 2017-11-14T02:37:17.720479032Z     return render('emails/' + self.template, dict({model: model_instance}, **self.extra_data))
web_1    | 2017-11-14T02:37:17.720481924Z   File "/app/plugins/uber/uber/decorators.py", line 274, in render
web_1    | 2017-11-14T02:37:17.720484838Z     rendered = template.render(data)
web_1    | 2017-11-14T02:37:17.720487562Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
web_1    | 2017-11-14T02:37:17.720490575Z     return self.environment.handle_exception(exc_info, True)
web_1    | 2017-11-14T02:37:17.720493337Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
web_1    | 2017-11-14T02:37:17.720496372Z     reraise(exc_type, exc_value, tb)
web_1    | 2017-11-14T02:37:17.720499035Z   File "/app/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
web_1    | 2017-11-14T02:37:17.720501985Z     raise value.with_traceback(tb)
web_1    | 2017-11-14T02:37:17.720504676Z   File "/app/plugins/art_show/art_show/templates/emails/art_show/declined.txt", line 1, in top-level template code
web_1    | 2017-11-14T02:37:17.720507721Z     {{ attendee.first_name }},
web_1    | 2017-11-14T02:37:17.720510420Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
web_1    | 2017-11-14T02:37:17.720513557Z     return getattr(obj, attribute)
web_1    | 2017-11-14T02:37:17.720516245Z jinja2.exceptions.UndefinedError: 'attendee' is undefined
web_1    | 2017-11-14T02:37:17.720768692Z error sending 'Your Midwest FurFest Art Show application has been declined' email to gingeegirls@gmail.com
web_1    | 2017-11-14T02:37:17.720777178Z Traceback (most recent call last):
web_1    | 2017-11-14T02:37:17.720780132Z   File "/app/plugins/uber/uber/automated_emails.py", line 78, in send_if_should
web_1    | 2017-11-14T02:37:17.720783094Z     self.really_send(model_inst)
web_1    | 2017-11-14T02:37:17.720785928Z   File "/app/plugins/uber/uber/automated_emails.py", line 156, in really_send
web_1    | 2017-11-14T02:37:17.720788808Z     self.render(model_instance), format,
web_1    | 2017-11-14T02:37:17.720791654Z   File "/app/plugins/uber/uber/automated_emails.py", line 140, in render
web_1    | 2017-11-14T02:37:17.720794473Z     return render('emails/' + self.template, dict({model: model_instance}, **self.extra_data))
web_1    | 2017-11-14T02:37:17.720810622Z   File "/app/plugins/uber/uber/decorators.py", line 274, in render
web_1    | 2017-11-14T02:37:17.720813529Z     rendered = template.render(data)
web_1    | 2017-11-14T02:37:17.720816052Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
web_1    | 2017-11-14T02:37:17.720818677Z     return self.environment.handle_exception(exc_info, True)
web_1    | 2017-11-14T02:37:17.720821244Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
web_1    | 2017-11-14T02:37:17.720823863Z     reraise(exc_type, exc_value, tb)
web_1    | 2017-11-14T02:37:17.720826372Z   File "/app/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
web_1    | 2017-11-14T02:37:17.720828960Z     raise value.with_traceback(tb)
web_1    | 2017-11-14T02:37:17.720831586Z   File "/app/plugins/art_show/art_show/templates/emails/art_show/declined.txt", line 1, in top-level template code
web_1    | 2017-11-14T02:37:17.720834291Z     {{ attendee.first_name }},
web_1    | 2017-11-14T02:37:17.720836813Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
web_1    | 2017-11-14T02:37:17.720839692Z     return getattr(obj, attribute)
web_1    | 2017-11-14T02:37:17.720842301Z jinja2.exceptions.UndefinedError: 'attendee' is undefined
web_1    | 2017-11-14T02:37:17.938765272Z error sending 'Your Midwest FurFest Art Show application has been declined' email to qubi1985@gmail.com
web_1    | 2017-11-14T02:37:17.938786666Z Traceback (most recent call last):
web_1    | 2017-11-14T02:37:17.938789950Z   File "/app/plugins/uber/uber/automated_emails.py", line 156, in really_send
web_1    | 2017-11-14T02:37:17.938793168Z     self.render(model_instance), format,
web_1    | 2017-11-14T02:37:17.938795668Z   File "/app/plugins/uber/uber/automated_emails.py", line 140, in render
web_1    | 2017-11-14T02:37:17.938798550Z     return render('emails/' + self.template, dict({model: model_instance}, **self.extra_data))
web_1    | 2017-11-14T02:37:17.938801133Z   File "/app/plugins/uber/uber/decorators.py", line 274, in render
web_1    | 2017-11-14T02:37:17.938803737Z     rendered = template.render(data)
web_1    | 2017-11-14T02:37:17.938806067Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
web_1    | 2017-11-14T02:37:17.938808688Z     return self.environment.handle_exception(exc_info, True)
web_1    | 2017-11-14T02:37:17.938811164Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
web_1    | 2017-11-14T02:37:17.938813813Z     reraise(exc_type, exc_value, tb)
web_1    | 2017-11-14T02:37:17.938816178Z   File "/app/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
web_1    | 2017-11-14T02:37:17.938818830Z     raise value.with_traceback(tb)
web_1    | 2017-11-14T02:37:17.938821187Z   File "/app/plugins/art_show/art_show/templates/emails/art_show/declined.txt", line 1, in top-level template code
web_1    | 2017-11-14T02:37:17.938823902Z     {{ attendee.first_name }},
web_1    | 2017-11-14T02:37:17.938826341Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
web_1    | 2017-11-14T02:37:17.938840185Z     return getattr(obj, attribute)
web_1    | 2017-11-14T02:37:17.938842809Z jinja2.exceptions.UndefinedError: 'attendee' is undefined
web_1    | 2017-11-14T02:37:17.939235892Z error sending 'Your Midwest FurFest Art Show application has been declined' email to REDACTED@gmail.com
web_1    | 2017-11-14T02:37:17.939246401Z Traceback (most recent call last):
web_1    | 2017-11-14T02:37:17.939249076Z   File "/app/plugins/uber/uber/automated_emails.py", line 78, in send_if_should
web_1    | 2017-11-14T02:37:17.939251866Z     self.really_send(model_inst)
web_1    | 2017-11-14T02:37:17.939254357Z   File "/app/plugins/uber/uber/automated_emails.py", line 156, in really_send
web_1    | 2017-11-14T02:37:17.939257116Z     self.render(model_instance), format,
web_1    | 2017-11-14T02:37:17.939259600Z   File "/app/plugins/uber/uber/automated_emails.py", line 140, in render
web_1    | 2017-11-14T02:37:17.939262478Z     return render('emails/' + self.template, dict({model: model_instance}, **self.extra_data))
web_1    | 2017-11-14T02:37:17.939265112Z   File "/app/plugins/uber/uber/decorators.py", line 274, in render
web_1    | 2017-11-14T02:37:17.939267791Z     rendered = template.render(data)
web_1    | 2017-11-14T02:37:17.939270246Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
web_1    | 2017-11-14T02:37:17.939272977Z     return self.environment.handle_exception(exc_info, True)
web_1    | 2017-11-14T02:37:17.939275518Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
web_1    | 2017-11-14T02:37:17.939278265Z     reraise(exc_type, exc_value, tb)
web_1    | 2017-11-14T02:37:17.939280698Z   File "/app/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
web_1    | 2017-11-14T02:37:17.939283424Z     raise value.with_traceback(tb)
web_1    | 2017-11-14T02:37:17.939285900Z   File "/app/plugins/art_show/art_show/templates/emails/art_show/declined.txt", line 1, in top-level template code
web_1    | 2017-11-14T02:37:17.939288737Z     {{ attendee.first_name }},
web_1    | 2017-11-14T02:37:17.939291204Z   File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
web_1    | 2017-11-14T02:37:17.939293931Z     return getattr(obj, attribute)
web_1    | 2017-11-14T02:37:17.939296357Z jinja2.exceptions.UndefinedError: 'attendee' is undefined
```

**Comment by jmdawson** [comment]
This is from 2017, and we've changed so much. I don't see this anymore.
