### ISSUE TITLE
Cannot Assign New Agent a second time

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#57]
On an artist application:

1. Get an agent code
1. Use code to sign up as agent for artist
1. Use artist app to assign new agent
1. Sign up as new agent for artist w/ yet another account
1. Try to use "assign new agent" button to kick off second agent, nothing happens.

**Comment by jmdawson** [comment]
Maybe related?
`celery-worker_1  | HINT:  Perhaps you meant to reference the column "art_show_application.agent_code".
celery-worker_1  |  [SQL: 'SELECT art_show_application.id AS art_show_application_id, art_show_application.attendee_id AS art_show_application_attendee_id, art_show_application.artist_name AS art_show_application_artist_name, art_show_application.panels AS art_show_application_panels, art_show_application.tables AS art_show_application_tables, art_show_application.description AS art_show_application_description, art_show_application.website AS art_show_application_website, art_show_application.special_needs AS art_show_application_special_needs, art_show_application.status AS art_show_application_status, art_show_application.delivery_method AS art_show_application_delivery_method, art_show_application.admin_notes AS art_show_application_admin_notes, art_show_application.agent_name AS art_show_application_agent_name, art_show_application.base_price AS art_show_application_base_price, art_show_application.overridden_price AS art_show_application_overridden_price \nFROM art_show_application'] (Background on this error at: http://sqlalche.me/e/f405)
celery-worker_1  | [2018-05-23 03:17:38,401: ERROR/ForkPoolWorker-2] Task uber.tasks.email.send_automated_emails[8f7a7ba3-95c3-43b0-a5ba-c878913d0a92] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) column art_show_application.agent_name does not exist\nLINE 1: ....admin_notes AS art_show_application_admin_notes, art_show_a...\n                                                             ^\nHINT:  Perhaps you meant to reference the column "art_show_application.agent_code".\n',)
celery-worker_1  | Traceback (most recent call last):
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
celery-worker_1  |     context)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
celery-worker_1  |     cursor.execute(statement, parameters)
celery-worker_1  | psycopg2.ProgrammingError: column art_show_application.agent_name does not exist
celery-worker_1  | LINE 1: ....admin_notes AS art_show_application_admin_notes, art_show_a...
celery-worker_1  |                                                              ^
celery-worker_1  | HINT:  Perhaps you meant to reference the column "art_show_application.agent_code".
celery-worker_1  | 
celery-worker_1  | 
celery-worker_1  | The above exception was the direct cause of the following exception:
celery-worker_1  | 
celery-worker_1  | Traceback (most recent call last):
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/celery/app/trace.py", line 374, in trace_task
celery-worker_1  |     R = retval = fun(*args, **kwargs)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/celery/app/trace.py", line 629, in __protected_call__
celery-worker_1  |     return self.run(*args, **kwargs)
celery-worker_1  |   File "/app/plugins/uber/uber/tasks/email.py", line 156, in send_automated_emails
celery-worker_1  |     for model_instance in model_instances:
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
celery-worker_1  |     return self._execute_and_instances(context)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
celery-worker_1  |     result = conn.execute(querycontext.statement, self._params)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 948, in execute
celery-worker_1  |     return meth(self, multiparams, params)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
celery-worker_1  |     return connection._execute_clauseelement(self, multiparams, params)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
celery-worker_1  |     compiled_sql, distilled_params
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
celery-worker_1  |     context)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
celery-worker_1  |     exc_info
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
celery-worker_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
celery-worker_1  |     raise value.with_traceback(tb)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
celery-worker_1  |     context)
celery-worker_1  |   File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
celery-worker_1  |     cursor.execute(statement, parameters)
celery-worker_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column art_show_application.agent_name does not exist
celery-worker_1  | LINE 1: ....admin_notes AS art_show_application_admin_notes, art_show_a...
celery-worker_1  |                                                              ^
celery-worker_1  | HINT:  Perhaps you meant to reference the column "art_show_application.agent_code".`

**Comment by jmdawson** [comment]
Works now.
